//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderDetail
    {
        public int id { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> totalPrice { get; set; }
        public Nullable<int> cake_id { get; set; }
        public Nullable<int> order_id { get; set; }
    
        public virtual cake cake { get; set; }
        public virtual order order { get; set; }
    }
}
